"""Auditable reviewed source recipes; no network. Run from data_processing/config."""
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from common import *
facts=[]
def add(pid,sid,entity,scope,topic,field,value,unit,anchor,page=None,**extra):
    facts.append(dict(project_id=pid,source_id=sid,entity_id=entity,parent_entity_id=pid,record_scope=scope,topic=topic,field=field,value_original=value,unit_original=unit,anchor=anchor,pdf_page=page,source_reference=f'PDF page {page}' if page else 'HTML body; exact anchor in saved extraction',measurement_type='reported_source_statement',**extra))
add('REAL_001','S021','REAL_001/INCLUDING_SPURS','project','01_authority','physical_progress','82','%','physical progress of the work is 82%',observation_date_original='2024-06',observation_period='2024-06',notes='Construction progress as of June 2024, including spurs. Not land acquisition.')
add('REAL_001','S021','REAL_001/INCLUDING_SPURS','project','01_authority','constructed_length_km','1136','km','cumulative length of 1136 km has been constructed',observation_date_original='2024-06')
add('REAL_001','S021','REAL_001/INCLUDING_SPURS','project','01_authority','completion_target','October, 2025','text','revised scheduled completion date is October, 2025',observation_date_original='2024-07-31',notes='Historical revised target, not actual completion date.')
add('REAL_003','S023','REAL_003','programme','01_authority','constructed_length_km','601','km','Out of 825 km, about 601 km has been completed',observation_date_original='2023-07-26',state='Uttarakhand')
add('REAL_003','S022','REAL_003','programme','07_climate_landscape','barrier_description','landslide mitigation at Kaliasaur ,Sonprayag, Maithana, Govindghat, Birahi','text','landslide mitigation at Kaliasaur ,Sonprayag, Maithana, Govindghat, Birahi',observation_date_original='2017-02-06',notes='Mitigation locations, not numeric hazard severity or completed mitigation.')
for value,unit,field,anchor,page,tenure in [
('75.89','ha','land_required_ha','acquisition/transfer of 75.89 ha of land',36,'temporary_and_permanent_combined'),
('29.79','ha','government_land_allotted_ha','government has allotted 29.79 ha land at Aarey Colony',36,'depot_government'),
('75.89','ha','land_acquired_ha','75.89 ha of land has been acquired',16,'temporary_and_permanent_combined')]:
    add('REAL_004','S024','REAL_004','project','02_state_district_land_acquisition',field,value,unit,anchor,page,land_tenure=tenure,observation_date_original='2020-12',notes='Historical December 2020 updated SIA; reported wording retained, not current status.')
for value,field,anchor,tenure in [('91.6032','land_required_ha','acquisition/transfer of 91.6032 ha of land','all'),('90.7573','land_required_ha','90.7573 ha is government land','government'),('0.8459','land_required_ha','0.8459 ha is private land','private'),('18.80','land_required_ha','18.80 ha is for permanent use','government_permanent'),('71.9573','land_required_ha','71.9573 ha is identified for temporary use','government_temporary'),('0.3207','land_required_ha','0.3207 ha is for permanent use','private_permanent'),('0.5252','land_required_ha','0.5252 ha is identified for temporary use','private_temporary')]:
    add('REAL_005','S034','REAL_005/PHASE_IV_PRIORITY','phase','02_state_district_land_acquisition',field,value,'ha',anchor,36,phase='IV priority',land_tenure=tenure,notes='Planned requirement/transfer, not acquired or paid status.')
add('REAL_005','S034','REAL_005/PHASE_IV_PRIORITY','phase','03_compensation','compensation_budget_inr','2389.68','INR_crore','total cost for the R&R implementation plan is INR. 2389.68 crore',84,phase='IV priority',notes='Indicative R&R budget. Not awarded or paid compensation.')
for value,field,anchor,tenure in [('28.14','land_required_ha','28.14 ha is to be acquired','all_permanent_including_depot'),('22.44','land_required_ha','22.44 ha belongs to government land','government_permanent_including_depot'),('5.70','land_required_ha','5.70 ha private land','private_permanent')]:
    add('REAL_006','S007','REAL_006/PHASE_II/CORRIDOR_4','corridor','02_state_district_land_acquisition',field,value,'ha',anchor,11,phase='II',corridor='4',land_tenure=tenure,observation_date_original='2018-12',notes='Table 2.1 cites DPR Dec 2018. Requirement, not acquisition achieved.')
add('REAL_006','S007','REAL_006/PHASE_II/CORRIDOR_4','corridor','04_rr_social_impact','affected_families','1031','count','impact on 1031 families',3,phase='II',corridor='4',notes='Projected affected families.')
add('REAL_006','S007','REAL_006/PHASE_II/CORRIDOR_4','corridor','03_compensation','compensation_budget_inr','477.80','INR_crore','compensation for land and assets to a tune of Rs 477.80 Crores',62,phase='II',corridor='4',observation_date_original='2020-04',notes='Preliminary estimate, not amount paid.')
add('REAL_006','S007','REAL_006/PHASE_II/CORRIDOR_4','corridor','03_compensation','RR_budget_inr','6.20','INR_crore','R&R assistances Rs. 6.20 crores',62,phase='II',corridor='4',observation_date_original='2020-04')
for value,tenure,anchor in [('163,875.5','all_permanent','163,875.5 sq mts land will be acquired permanently'),('108,282.5','government_permanent','108,282.5 sq mts are government land'),('55,593','private_permanent','55,593 sq mts of land is private'),('288,492','government_temporary','288,492 sq mts of land will be acquired temporarily')]:
    add('REAL_006','S008','REAL_006/PHASE_II/CORRIDOR_5','corridor','02_state_district_land_acquisition','land_required_ha',value,'m2',anchor,4,phase='II',corridor='5',land_tenure=tenure,notes='Cover and this page explicitly Corridor 5. Later conflicting page headers held for review.')
# Same document disagrees on stations; intentionally preserve both for conflict report.
add('REAL_006','S008','REAL_006/PHASE_II/CORRIDOR_5','corridor','09_validation','station_count','29','count','including 29 stations',4,phase='II',corridor='5',notes='Conflict with page 14: 30 stations.')
add('REAL_006','S008','REAL_006/PHASE_II/CORRIDOR_5','corridor','09_validation','station_count','30','count','including 30 stations',14,phase='II',corridor='5',notes='Conflict with page 4: 29 stations.')
add('REAL_007','S009','REAL_007','programme','01_authority','constructed_length_km','18,714','km','18,714 km has been constructed',observation_date_original='2024-10-31',notes='Programme-wide context only.')
add('REAL_007','S009','REAL_007','programme','01_authority','awarded_length_km','26,425','km','total length of 26,425 km have been awarded',observation_date_original='2024-10-31')
add('REAL_008','S017','REAL_008','project','01_authority','constructed_tunnel_length_km','12','km','approximately 12 km of the tunnel has been completed',observation_date_original='2025-11-20',notes='Approximate reported length; no percentage derived from unrelated design lengths.')
add('REAL_008','S017','REAL_008','project','01_authority','completion_target','February 2028','text','target for project completion is February 2028',observation_date_original='2025-11-20')
add('REAL_008','S017','REAL_008','project','07_climate_landscape','barrier_description','pace of work varies depending on the type of rock strata encountered','text','pace of work varies depending on the type of rock strata encountered',observation_date_original='2025-11-20')
add('REAL_008','S036','REAL_008/HISTORICAL_DESIGN','project','07_climate_landscape','access_constraint','Work not possible at rest of the faces for four months during the winter period.','text','Work not possible at rest of the faces for four months during the winter period.',4,notes='Undated historical design presentation; not asserted as current restriction.')
add('REAL_009','S028','REAL_009/APPROVAL_PACKAGE_III','package','06_approvals','forest_diversion_area_ha','26.877','ha','26.877ha ReservedForestland',1,package_number='III',state='Maharashtra',district='Aurangabad',observation_date_original='2018-02-08',notes='Forest approval package III; not interchangeable with civil-contract package numbers.')
add('REAL_009','S028','REAL_009/APPROVAL_PACKAGE_III','package','06_approvals','approval_status','in-principle','text',"accords'in-principle'",1,package_number='III',state='Maharashtra',district='Aurangabad',observation_date_original='2018-02-08',notes='Stage I only; no Stage II completion inferred.')
add('REAL_010','S013','REAL_010/EDFC_I_II_III','corridor','02_state_district_land_acquisition','land_required_ha','3600','ha','3,6 00 hectares',6,observation_date_original='2018-12',notes='Approximate total for EDFC I/II/III, not Prayagraj-specific; not acquired total.')
add('REAL_010','S013','REAL_010/DIRECT_PURCHASE_POLICY_SCOPE','corridor','02_state_district_land_acquisition','land_to_be_acquired_ha','3.05','ha','3.05 hectares in about 20 villages',6,observation_date_original='2018-12',notes='Assessed direct-purchase requirement, mostly EDFC I. Not whole-corridor requirement.')
add('REAL_010','S013','REAL_010/DIRECT_PURCHASE_POLICY_SCOPE','corridor','03_compensation','landowners_count','250','count','about 250 land owners',6,observation_date_original='2018-12',notes='Approximate policy assessment; not independently confirmed beneficiary count.')
# Scope-aware Bharatmala package barriers from exact cells; no invented court case identifiers.
p=next((ROOT/'project_research').glob('*/*/S018_extracted.json'))
cells=read_json(p)['cells']; index={(c['page'],c['table'],c['row'],c['column']):c for c in cells}
for c in cells:
    if c.get('column')!=10 or c.get('page')!=2 or c.get('row',0)<3:continue
    r=c['row']; name=index.get((2,1,r,2)); serial=index.get((2,1,r,1))
    if not name or not serial or not serial['value_original'].isdigit() or c['value_original'].strip() in ('','_'):continue
    add('REAL_007','S018','REAL_007/KA/ANNEXURE_ROW_'+serial['value_original'],'package','08_procurement_contracts','barrier_description',c['value_original'],'text',c['value_original'],2,state='Karnataka',package_number=None,package_name_as_source=name['value_original'],source_cell={'table':1,'row':r,'column':10},observation_date_original='2026-02-05',notes='Official annexure row identifies package; local row ID is not an official package number. Reason for construction delay does not establish a target label.')
add('REAL_003','S038','REAL_003/CASE/CA_10930_2018','case','05_legal','case_number','Civil Appeal No 10930 of 2018','text','Civil Appeal No 10930 of 2018',1,case_number='Civil Appeal No 10930 of 2018',observation_date_original='2021-12-14')
add('REAL_003','S038','REAL_003/CASE/CA_10930_2018','case','05_legal','court','SUPREME COURT OF INDIA','text','SUPREME COURT OF INDIA',1,case_number='Civil Appeal No 10930 of 2018',observation_date_original='2021-12-14')
add('REAL_003','S038','REAL_003/CASE/MA_1925_2020','case','05_legal','case_status','disposed of','text','MA No 1925 of 2020 is disposed of',82,case_number='MA No 1925 of 2020 in CA 10930 of 2018',observation_date_original='2021-12-14',notes='Status of this application on judgment date only; not current status of all litigation.')
for field,value,anchor in [('row_available_pct','100.00%','100.00% 30.99% 27.87%'),('physical_progress','30.99%','100.00% 30.99% 27.87%'),('financial_progress','27.87%','100.00% 30.99% 27.87%')]:
    add('REAL_008','S040','REAL_008/TUNNEL_AND_CONNECTING_ROAD','project','01_authority',field,value,'%',anchor,12,observation_date_original='2023-04-30',notes='PDF page 12 row 5, Zojila tunnel plus connecting road. ROW availability is NOT land acquisition completion; adjacent Z-Morh row excluded.')
add('REAL_008','S040','REAL_008/TUNNEL_AND_CONNECTING_ROAD','project','08_procurement_contracts','contractor_name','Megha Engineering & Infrastructures Ltd (MEIL)','text','Megha Engineering & Infrastructures Ltd (MEIL)',12,observation_date_original='2023-04-30')
write_json(CONFIG/'reviewed_observations.json',facts)
print('Wrote',len(facts),'reviewed recipes')
