export const demoProjects = [
  {
    project_id: "LA-MH-0125",
    project_name: "Nashik–Pune Greenfield Corridor",
    project_type: "National Highway",
    state: "Maharashtra",
    district: "Nashik",
    current_stage: "Compensation",
    affected_families: 274,
    land_required_ha: 125.4,
    compensation_percentage: 54,
    possession_percentage: 32,
    days_in_current_stage: 127,
    delay_probability: 0.82,
    risk_level: "HIGH",
    risk_color: "#ef6262",
    latitude: 20.011,
    longitude: 73.79,
  },
  {
    project_id: "LA-UP-0872",
    project_name: "Ganga Expressway Link Package",
    project_type: "Expressway",
    state: "Uttar Pradesh",
    district: "Hardoi",
    current_stage: "Possession",
    affected_families: 188,
    land_required_ha: 96.8,
    compensation_percentage: 68,
    possession_percentage: 51,
    days_in_current_stage: 96,
    delay_probability: 0.67,
    risk_level: "MEDIUM",
    risk_color: "#d89635",
    latitude: 27.394,
    longitude: 80.132,
  },
  {
    project_id: "LA-GJ-0441",
    project_name: "Ahmedabad Freight Logistics Hub",
    project_type: "Logistics",
    state: "Gujarat",
    district: "Ahmedabad",
    current_stage: "Award",
    affected_families: 86,
    land_required_ha: 72.5,
    compensation_percentage: 83,
    possession_percentage: 74,
    days_in_current_stage: 61,
    delay_probability: 0.31,
    risk_level: "LOW",
    risk_color: "#24a579",
    latitude: 23.022,
    longitude: 72.571,
  },
  {
    project_id: "LA-KA-0318",
    project_name: "Bengaluru Suburban Rail Phase II",
    project_type: "Railway",
    state: "Karnataka",
    district: "Bengaluru Urban",
    current_stage: "Survey",
    affected_families: 341,
    land_required_ha: 88.2,
    compensation_percentage: 46,
    possession_percentage: 24,
    days_in_current_stage: 142,
    delay_probability: 0.76,
    risk_level: "HIGH",
    risk_color: "#ef6262",
    latitude: 12.972,
    longitude: 77.594,
  },
  {
    project_id: "LA-WB-0207",
    project_name: "Kolkata Industrial Connector",
    project_type: "Industrial Corridor",
    state: "West Bengal",
    district: "Howrah",
    current_stage: "Compensation",
    affected_families: 156,
    land_required_ha: 64.9,
    compensation_percentage: 72,
    possession_percentage: 58,
    days_in_current_stage: 84,
    delay_probability: 0.54,
    risk_level: "MEDIUM",
    risk_color: "#d89635",
    latitude: 22.595,
    longitude: 88.263,
  },
  {
    project_id: "LA-TN-0164",
    project_name: "Chennai Peripheral Ring Road",
    project_type: "Ring Road",
    state: "Tamil Nadu",
    district: "Chengalpattu",
    current_stage: "Possession",
    affected_families: 112,
    land_required_ha: 79.1,
    compensation_percentage: 89,
    possession_percentage: 81,
    days_in_current_stage: 48,
    delay_probability: 0.24,
    risk_level: "LOW",
    risk_color: "#24a579",
    latitude: 12.681,
    longitude: 79.988,
  },
] as const;
